apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: calculator-ui
  template:
    metadata:
      labels:
        app: calculator-ui
    spec:
      containers:
      - image: ghcr.io/holovachov/khai-lab:latest
        name: calculator-ui
        ports:
        - containerPort: 80