replicaCount: 1

image:
  repository: ghcr.io/holovachov/khai-lab
  tag: 0.1
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - calculator.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}